language: csharp
solution: KeySAVCoreJS.sln
before_install:
- openssl aes-256-cbc -K $encrypted_a02c42a85227_key -iv $encrypted_a02c42a85227_iv
  -in DuoCode.lic.enc -out KeySAVCoreJS/DuoCode.lic -d
after_success:
- cd KeySAVCoreJS/scripts
- npm install
- npm run publish
